# ruff: noqa
# fmt: off
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: enterprise_genai/rpc/retrieval/v1/retrieval.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'enterprise_genai/rpc/retrieval/v1/retrieval.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1enterprise_genai/rpc/retrieval/v1/retrieval.proto\x12!enterprise_genai.rpc.retrieval.v1\"t\n\x10RetrievalRequest\x12\x1c\n\x0f\x64\x61taset_version\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x10\n\x08question\x18\x02 \x01(\t\x12\x12\n\x05top_k\x18\x03 \x01(\rH\x01\x88\x01\x01\x42\x12\n\x10_dataset_versionB\x08\n\x06_top_k\"\xe0\x01\n\x0cRetrievalHit\x12\x0c\n\x04rank\x18\x01 \x01(\r\x12\x10\n\x08\x63hunk_id\x18\x02 \x01(\t\x12\x13\n\x0b\x65vidence_id\x18\x03 \x01(\t\x12\x13\n\x0b\x64ocument_id\x18\x04 \x01(\t\x12\x0c\n\x04text\x18\x05 \x01(\t\x12\x17\n\x0fsource_fact_ids\x18\x06 \x03(\t\x12\x11\n\trrf_score\x18\x07 \x01(\x01\x12\x16\n\tbm25_rank\x18\x08 \x01(\rH\x00\x88\x01\x01\x12\x17\n\ndense_rank\x18\t \x01(\rH\x01\x88\x01\x01\x42\x0c\n\n_bm25_rankB\r\n\x0b_dense_rank\"Q\n\x10RetrievalPayload\x12=\n\x04hits\x18\x01 \x03(\x0b\x32/.enterprise_genai.rpc.retrieval.v1.RetrievalHit\"\xd0\x01\n\x11RetrievalResponse\x12\x42\n\x06status\x18\x01 \x01(\x0e\x32\x32.enterprise_genai.rpc.retrieval.v1.ExecutionStatus\x12\x44\n\x07payload\x18\x02 \x01(\x0b\x32\x33.enterprise_genai.rpc.retrieval.v1.RetrievalPayload\x12\x13\n\x0b\x64uration_ms\x18\x03 \x01(\x01\x12\x12\n\x05\x65rror\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_error*\x84\x01\n\x0f\x45xecutionStatus\x12 \n\x1c\x45XECUTION_STATUS_UNSPECIFIED\x10\x00\x12\x17\n\x13\x45XECUTION_STATUS_OK\x10\x01\x12\x1a\n\x16\x45XECUTION_STATUS_EMPTY\x10\x02\x12\x1a\n\x16\x45XECUTION_STATUS_ERROR\x10\x03\x32\x89\x01\n\x10RetrievalService\x12u\n\x08Retrieve\x12\x33.enterprise_genai.rpc.retrieval.v1.RetrievalRequest\x1a\x34.enterprise_genai.rpc.retrieval.v1.RetrievalResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'enterprise_genai.rpc.retrieval.v1.retrieval_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXECUTIONSTATUS']._serialized_start=728
  _globals['_EXECUTIONSTATUS']._serialized_end=860
  _globals['_RETRIEVALREQUEST']._serialized_start=88
  _globals['_RETRIEVALREQUEST']._serialized_end=204
  _globals['_RETRIEVALHIT']._serialized_start=207
  _globals['_RETRIEVALHIT']._serialized_end=431
  _globals['_RETRIEVALPAYLOAD']._serialized_start=433
  _globals['_RETRIEVALPAYLOAD']._serialized_end=514
  _globals['_RETRIEVALRESPONSE']._serialized_start=517
  _globals['_RETRIEVALRESPONSE']._serialized_end=725
  _globals['_RETRIEVALSERVICE']._serialized_start=863
  _globals['_RETRIEVALSERVICE']._serialized_end=1000
# @@protoc_insertion_point(module_scope)
