"""add deterministic retrieval chunks

Revision ID: 8a0f69a3baf1
Revises: e890a5c0198c
Create Date: 2026-09-01 20:08:38.211428

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8a0f69a3baf1"
down_revision: str | Sequence[str] | None = "e890a5c0198c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_evidence_blocks_document_evidence",
        "evidence_blocks",
        ["dataset_version", "document_id", "evidence_id"],
    )
    op.create_table(
        "chunks",
        sa.Column("dataset_version", sa.String(length=64), nullable=False),
        sa.Column("chunk_id", sa.String(length=68), nullable=False),
        sa.Column("document_id", sa.String(length=128), nullable=False),
        sa.Column("evidence_id", sa.String(length=128), nullable=False),
        sa.Column("chunk_ordinal", sa.Integer(), nullable=False),
        sa.Column("strategy_version", sa.String(length=64), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("text_sha256", sa.String(length=64), nullable=False),
        sa.Column("character_count", sa.Integer(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.CheckConstraint("text_sha256 ~ '^[0-9a-f]{64}$'", name="ck_chunks_text_sha256"),
        sa.CheckConstraint("char_length(strategy_version) > 0", name="ck_chunks_strategy_version"),
        sa.CheckConstraint("char_length(text) > 0", name="ck_chunks_text"),
        sa.CheckConstraint("character_count > 0", name="ck_chunks_character_count"),
        sa.CheckConstraint("chunk_ordinal >= 0", name="ck_chunks_ordinal"),
        sa.CheckConstraint("word_count > 0", name="ck_chunks_word_count"),
        sa.ForeignKeyConstraint(
            ["dataset_version", "document_id", "evidence_id"],
            [
                "evidence_blocks.dataset_version",
                "evidence_blocks.document_id",
                "evidence_blocks.evidence_id",
            ],
            name="fk_chunks_evidence",
        ),
        sa.PrimaryKeyConstraint("dataset_version", "chunk_id"),
        sa.UniqueConstraint(
            "dataset_version", "chunk_id", "evidence_id", name="uq_chunks_chunk_evidence"
        ),
        sa.UniqueConstraint(
            "dataset_version",
            "evidence_id",
            "strategy_version",
            "chunk_ordinal",
            name="uq_chunks_evidence_strategy_ordinal",
        ),
    )
    op.create_index(
        "ix_chunks_document", "chunks", ["dataset_version", "document_id"], unique=False
    )
    op.create_index(
        "ix_chunks_evidence", "chunks", ["dataset_version", "evidence_id"], unique=False
    )
    op.create_index(
        "ix_chunks_strategy", "chunks", ["dataset_version", "strategy_version"], unique=False
    )
    op.create_table(
        "chunk_source_facts",
        sa.Column("dataset_version", sa.String(length=64), nullable=False),
        sa.Column("chunk_id", sa.String(length=68), nullable=False),
        sa.Column("evidence_id", sa.String(length=128), nullable=False),
        sa.Column("source_fact_id", sa.String(length=128), nullable=False),
        sa.Column("source_ordinal", sa.Integer(), nullable=False),
        sa.CheckConstraint("source_ordinal >= 0", name="ck_chunk_source_facts_ordinal"),
        sa.ForeignKeyConstraint(
            ["dataset_version", "chunk_id", "evidence_id"],
            ["chunks.dataset_version", "chunks.chunk_id", "chunks.evidence_id"],
            name="fk_chunk_source_facts_chunk",
        ),
        sa.ForeignKeyConstraint(
            ["dataset_version", "evidence_id", "source_fact_id"],
            [
                "evidence_source_facts.dataset_version",
                "evidence_source_facts.evidence_id",
                "evidence_source_facts.source_fact_id",
            ],
            name="fk_chunk_source_facts_evidence_fact",
        ),
        sa.PrimaryKeyConstraint("dataset_version", "chunk_id", "evidence_id", "source_fact_id"),
        sa.UniqueConstraint(
            "dataset_version", "chunk_id", "source_ordinal", name="uq_chunk_source_facts_ordinal"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chunk_source_facts")
    op.drop_index("ix_chunks_strategy", table_name="chunks")
    op.drop_index("ix_chunks_evidence", table_name="chunks")
    op.drop_index("ix_chunks_document", table_name="chunks")
    op.drop_table("chunks")
    op.drop_constraint(
        "uq_evidence_blocks_document_evidence",
        "evidence_blocks",
        type_="unique",
    )
    # ### end Alembic commands ###
