"""create Northstar relational schema

Revision ID: e890a5c0198c
Revises:
Create Date: 2026-09-01 19:08:27.549101

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e890a5c0198c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dataset_versions",
        sa.Column("dataset_version", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=64), nullable=False),
        sa.Column("random_seed", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("dataset_version"),
    )
    op.create_table(
        "canonical_facts",
        sa.Column("dataset_version", sa.String(length=64), nullable=False),
        sa.Column("fact_id", sa.String(length=128), nullable=False),
        sa.Column("fact_type", sa.String(length=64), nullable=False),
        sa.CheckConstraint("char_length(fact_type) > 0", name="ck_canonical_facts_fact_type"),
        sa.ForeignKeyConstraint(
            ["dataset_version"],
            ["dataset_versions.dataset_version"],
        ),
        sa.PrimaryKeyConstraint("dataset_version", "fact_id"),
    )
    op.create_table(
        "customers",
        sa.Column("dataset_version", sa.String(length=64), nullable=False),
        sa.Column("customer_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("industry", sa.String(length=255), nullable=False),
        sa.Column("country", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_version"],
            ["dataset_versions.dataset_version"],
        ),
        sa.PrimaryKeyConstraint("dataset_version", "customer_id"),
    )
    op.create_table(
        "firms",
        sa.Column("dataset_version", sa.String(length=64), nullable=False),
        sa.Column("firm_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_version"],
            ["dataset_versions.dataset_version"],
        ),
        sa.PrimaryKeyConstraint("dataset_version", "firm_id"),
    )
    op.create_table(
        "suppliers",
        sa.Column("dataset_version", sa.String(length=64), nullable=False),
        sa.Column("supplier_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=255), nullable=False),
        sa.Column("country", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_version"],
            ["dataset_versions.dataset_version"],
        ),
        sa.PrimaryKeyConstraint("dataset_version", "supplier_id"),
    )
    op.create_table(
        "funds",
        sa.Column("dataset_version", sa.String(length=64), nullable=False),
        sa.Column("fund_id", sa.String(length=64), nullable=False),
        sa.Column("firm_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("vintage_year", sa.Integer(), nullable=False),
        sa.Column("committed_capital_usd", sa.BigInteger(), nullable=False),
        sa.CheckConstraint("committed_capital_usd > 0", name="ck_funds_committed_capital_usd"),
        sa.ForeignKeyConstraint(
            ["dataset_version", "firm_id"],
            ["firms.dataset_version", "firms.firm_id"],
            name="fk_funds_firm",
        ),
        sa.PrimaryKeyConstraint("dataset_version", "fund_id"),
    )
    op.create_table(
        "companies",
        sa.Column("dataset_version", sa.String(length=64), nullable=False),
        sa.Column("company_id", sa.String(length=64), nullable=False),
        sa.Column("fund_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("industry", sa.String(length=255), nullable=False),
        sa.Column("headquarters_country", sa.String(length=128), nullable=False),
        sa.Column("investment_date", sa.Date(), nullable=False),
        sa.Column("ownership_pct", sa.Numeric(precision=6, scale=3), nullable=False),
        sa.CheckConstraint(
            "ownership_pct >= 0 AND ownership_pct <= 100", name="ck_companies_ownership_pct"
        ),
        sa.ForeignKeyConstraint(
            ["dataset_version", "fund_id"],
            ["funds.dataset_version", "funds.fund_id"],
            name="fk_companies_fund",
        ),
        sa.PrimaryKeyConstraint("dataset_version", "company_id"),
    )
    op.create_table(
        "company_customers",
        sa.Column("dataset_version", sa.String(length=64), nullable=False),
        sa.Column("relationship_id", sa.String(length=64), nullable=False),
        sa.Column("company_id", sa.String(length=64), nullable=False),
        sa.Column("customer_id", sa.String(length=64), nullable=False),
        sa.Column("revenue_share_pct", sa.Numeric(precision=6, scale=3), nullable=False),
        sa.Column("relationship_start_date", sa.Date(), nullable=False),
        sa.Column("relationship_status", sa.String(length=16), nullable=False),
        sa.CheckConstraint(
            "relationship_status IN ('active', 'at_risk', 'ended')",
            name="ck_company_customers_relationship_status",
        ),
        sa.CheckConstraint(
            "revenue_share_pct >= 0 AND revenue_share_pct <= 100",
            name="ck_company_customers_revenue_share_pct",
        ),
        sa.ForeignKeyConstraint(
            ["dataset_version", "company_id"],
            ["companies.dataset_version", "companies.company_id"],
            name="fk_company_customers_company",
        ),
        sa.ForeignKeyConstraint(
            ["dataset_version", "customer_id"],
            ["customers.dataset_version", "customers.customer_id"],
            name="fk_company_customers_customer",
        ),
        sa.PrimaryKeyConstraint("dataset_version", "relationship_id"),
    )
    op.create_table(
        "company_suppliers",
        sa.Column("dataset_version", sa.String(length=64), nullable=False),
        sa.Column("relationship_id", sa.String(length=64), nullable=False),
        sa.Column("company_id", sa.String(length=64), nullable=False),
        sa.Column("supplier_id", sa.String(length=64), nullable=False),
        sa.Column("spend_share_pct", sa.Numeric(precision=6, scale=3), nullable=False),
        sa.Column("criticality", sa.String(length=16), nullable=False),
        sa.Column("single_source", sa.Boolean(), nullable=False),
        sa.Column("relationship_status", sa.String(length=16), nullable=False),
        sa.CheckConstraint(
            "criticality IN ('low', 'medium', 'high', 'critical')",
            name="ck_company_suppliers_criticality",
        ),
        sa.CheckConstraint(
            "relationship_status IN ('active', 'at_risk', 'ended')",
            name="ck_company_suppliers_relationship_status",
        ),
        sa.CheckConstraint(
            "spend_share_pct >= 0 AND spend_share_pct <= 100",
            name="ck_company_suppliers_spend_share_pct",
        ),
        sa.ForeignKeyConstraint(
            ["dataset_version", "company_id"],
            ["companies.dataset_version", "companies.company_id"],
            name="fk_company_suppliers_company",
        ),
        sa.ForeignKeyConstraint(
            ["dataset_version", "supplier_id"],
            ["suppliers.dataset_version", "suppliers.supplier_id"],
            name="fk_company_suppliers_supplier",
        ),
        sa.PrimaryKeyConstraint("dataset_version", "relationship_id"),
    )
    op.create_table(
        "documents",
        sa.Column("dataset_version", sa.String(length=64), nullable=False),
        sa.Column("document_id", sa.String(length=128), nullable=False),
        sa.Column("company_id", sa.String(length=64), nullable=False),
        sa.Column("document_type", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("document_date", sa.Date(), nullable=False),
        sa.Column("confidentiality", sa.String(length=16), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "confidentiality IN ('internal', 'confidential', 'restricted')",
            name="ck_documents_confidentiality",
        ),
        sa.CheckConstraint(
            "document_type IN "
            "('investment_committee_memo', "
            "'quarterly_management_report', "
            "'board_update', 'risk_review', "
            "'incident_report', 'supplier_review', "
            "'customer_review', 'strategy_memo')",
            name="ck_documents_type",
        ),
        sa.CheckConstraint("version >= 1", name="ck_documents_version"),
        sa.ForeignKeyConstraint(
            ["dataset_version", "company_id"],
            ["companies.dataset_version", "companies.company_id"],
            name="fk_documents_company",
        ),
        sa.PrimaryKeyConstraint("dataset_version", "document_id"),
    )
    op.create_index(
        "ix_documents_company_date",
        "documents",
        ["dataset_version", "company_id", "document_date"],
        unique=False,
    )
    op.create_table(
        "financial_metrics",
        sa.Column("dataset_version", sa.String(length=64), nullable=False),
        sa.Column("company_id", sa.String(length=64), nullable=False),
        sa.Column("period", sa.String(length=6), nullable=False),
        sa.Column("revenue_usd", sa.BigInteger(), nullable=False),
        sa.Column("ebitda_usd", sa.BigInteger(), nullable=False),
        sa.Column("gross_margin_pct", sa.Numeric(precision=6, scale=3), nullable=False),
        sa.Column("net_retention_pct", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("customer_count", sa.Integer(), nullable=True),
        sa.Column("employee_count", sa.Integer(), nullable=True),
        sa.CheckConstraint("period ~ '^[0-9]{4}Q[1-4]$'", name="ck_financial_metrics_period"),
        sa.CheckConstraint(
            "customer_count IS NULL OR customer_count >= 0",
            name="ck_financial_metrics_customer_count",
        ),
        sa.CheckConstraint(
            "employee_count IS NULL OR employee_count >= 0",
            name="ck_financial_metrics_employee_count",
        ),
        sa.CheckConstraint(
            "gross_margin_pct >= 0 AND gross_margin_pct <= 100",
            name="ck_financial_metrics_gross_margin_pct",
        ),
        sa.CheckConstraint(
            "net_retention_pct IS NULL OR (net_retention_pct >= 0 AND net_retention_pct <= 300)",
            name="ck_financial_metrics_net_retention_pct",
        ),
        sa.CheckConstraint("revenue_usd >= 0", name="ck_financial_metrics_revenue_usd"),
        sa.ForeignKeyConstraint(
            ["dataset_version", "company_id"],
            ["companies.dataset_version", "companies.company_id"],
            name="fk_financial_metrics_company",
        ),
        sa.PrimaryKeyConstraint("dataset_version", "company_id", "period"),
    )
    op.create_index(
        "ix_financial_metrics_period",
        "financial_metrics",
        ["dataset_version", "period"],
        unique=False,
    )
    op.create_table(
        "geographic_exposures",
        sa.Column("dataset_version", sa.String(length=64), nullable=False),
        sa.Column("exposure_id", sa.String(length=64), nullable=False),
        sa.Column("company_id", sa.String(length=64), nullable=False),
        sa.Column("country", sa.String(length=128), nullable=False),
        sa.Column("exposure_type", sa.String(length=32), nullable=False),
        sa.Column("exposure_pct", sa.Numeric(precision=6, scale=3), nullable=False),
        sa.CheckConstraint(
            "exposure_type IN ('revenue', 'supplier', 'employee', 'manufacturing', 'project')",
            name="ck_geographic_exposures_type",
        ),
        sa.CheckConstraint(
            "exposure_pct >= 0 AND exposure_pct <= 100", name="ck_geographic_exposures_pct"
        ),
        sa.ForeignKeyConstraint(
            ["dataset_version", "company_id"],
            ["companies.dataset_version", "companies.company_id"],
            name="fk_geographic_exposures_company",
        ),
        sa.PrimaryKeyConstraint("dataset_version", "exposure_id"),
    )
    op.create_table(
        "operational_metrics",
        sa.Column("dataset_version", sa.String(length=64), nullable=False),
        sa.Column("metric_id", sa.String(length=128), nullable=False),
        sa.Column("company_id", sa.String(length=64), nullable=False),
        sa.Column("period", sa.String(length=6), nullable=False),
        sa.Column("metric_name", sa.String(length=128), nullable=False),
        sa.Column("metric_value", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("unit", sa.String(length=64), nullable=False),
        sa.CheckConstraint("period ~ '^[0-9]{4}Q[1-4]$'", name="ck_operational_metrics_period"),
        sa.ForeignKeyConstraint(
            ["dataset_version", "company_id"],
            ["companies.dataset_version", "companies.company_id"],
            name="fk_operational_metrics_company",
        ),
        sa.PrimaryKeyConstraint("dataset_version", "metric_id"),
        sa.UniqueConstraint(
            "dataset_version",
            "company_id",
            "period",
            "metric_name",
            name="uq_operational_metrics_company_period_metric",
        ),
    )
    op.create_index(
        "ix_operational_metrics_period",
        "operational_metrics",
        ["dataset_version", "period"],
        unique=False,
    )
    op.create_table(
        "risks",
        sa.Column("dataset_version", sa.String(length=64), nullable=False),
        sa.Column("risk_id", sa.String(length=64), nullable=False),
        sa.Column("company_id", sa.String(length=64), nullable=False),
        sa.Column("risk_category", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("identified_date", sa.Date(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "severity IN ('low', 'medium', 'high', 'critical')", name="ck_risks_severity"
        ),
        sa.CheckConstraint(
            "status IN ('open', 'monitoring', 'mitigated', 'closed')", name="ck_risks_status"
        ),
        sa.ForeignKeyConstraint(
            ["dataset_version", "company_id"],
            ["companies.dataset_version", "companies.company_id"],
            name="fk_risks_company",
        ),
        sa.PrimaryKeyConstraint("dataset_version", "risk_id"),
    )
    op.create_table(
        "transactions",
        sa.Column("dataset_version", sa.String(length=64), nullable=False),
        sa.Column("transaction_id", sa.String(length=64), nullable=False),
        sa.Column("company_id", sa.String(length=64), nullable=False),
        sa.Column("transaction_type", sa.String(length=128), nullable=False),
        sa.Column("announcement_date", sa.Date(), nullable=False),
        sa.Column("close_date", sa.Date(), nullable=True),
        sa.Column("value_usd", sa.BigInteger(), nullable=True),
        sa.Column("counterparty", sa.String(length=255), nullable=False),
        sa.CheckConstraint("value_usd IS NULL OR value_usd > 0", name="ck_transactions_value_usd"),
        sa.ForeignKeyConstraint(
            ["dataset_version", "company_id"],
            ["companies.dataset_version", "companies.company_id"],
            name="fk_transactions_company",
        ),
        sa.PrimaryKeyConstraint("dataset_version", "transaction_id"),
    )
    op.create_table(
        "evidence_blocks",
        sa.Column("dataset_version", sa.String(length=64), nullable=False),
        sa.Column("evidence_id", sa.String(length=128), nullable=False),
        sa.Column("document_id", sa.String(length=128), nullable=False),
        sa.Column("evidence_ordinal", sa.Integer(), nullable=False),
        sa.Column("heading", sa.String(length=255), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.CheckConstraint("char_length(text) > 0", name="ck_evidence_blocks_text"),
        sa.CheckConstraint("evidence_ordinal >= 0", name="ck_evidence_blocks_ordinal"),
        sa.ForeignKeyConstraint(
            ["dataset_version", "document_id"],
            ["documents.dataset_version", "documents.document_id"],
            name="fk_evidence_blocks_document",
        ),
        sa.PrimaryKeyConstraint("dataset_version", "evidence_id"),
        sa.UniqueConstraint(
            "dataset_version",
            "document_id",
            "evidence_ordinal",
            name="uq_evidence_blocks_document_ordinal",
        ),
    )
    op.create_table(
        "evidence_source_facts",
        sa.Column("dataset_version", sa.String(length=64), nullable=False),
        sa.Column("evidence_id", sa.String(length=128), nullable=False),
        sa.Column("source_fact_id", sa.String(length=128), nullable=False),
        sa.Column("source_ordinal", sa.Integer(), nullable=False),
        sa.CheckConstraint("source_ordinal >= 0", name="ck_evidence_source_facts_ordinal"),
        sa.ForeignKeyConstraint(
            ["dataset_version", "evidence_id"],
            ["evidence_blocks.dataset_version", "evidence_blocks.evidence_id"],
            name="fk_evidence_source_facts_evidence",
        ),
        sa.ForeignKeyConstraint(
            ["dataset_version", "source_fact_id"],
            ["canonical_facts.dataset_version", "canonical_facts.fact_id"],
            name="fk_evidence_source_facts_fact",
        ),
        sa.PrimaryKeyConstraint("dataset_version", "evidence_id", "source_fact_id"),
        sa.UniqueConstraint(
            "dataset_version",
            "evidence_id",
            "source_ordinal",
            name="uq_evidence_source_facts_ordinal",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("evidence_source_facts")
    op.drop_table("evidence_blocks")
    op.drop_table("transactions")
    op.drop_table("risks")
    op.drop_index("ix_operational_metrics_period", table_name="operational_metrics")
    op.drop_table("operational_metrics")
    op.drop_table("geographic_exposures")
    op.drop_index("ix_financial_metrics_period", table_name="financial_metrics")
    op.drop_table("financial_metrics")
    op.drop_index("ix_documents_company_date", table_name="documents")
    op.drop_table("documents")
    op.drop_table("company_suppliers")
    op.drop_table("company_customers")
    op.drop_table("companies")
    op.drop_table("funds")
    op.drop_table("suppliers")
    op.drop_table("firms")
    op.drop_table("customers")
    op.drop_table("canonical_facts")
    op.drop_table("dataset_versions")
    # ### end Alembic commands ###
